# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:

env:
  GITHUB_NAME: Bob
  GITHUB_EMAIL: 971822071@qq.com

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: ${{ vars.ALIYUN_OSS_ENDPOINT }}
        access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

    - run: ossutil cp -rf readme.md ${{ vars.ALIYUN_OSS_PATH }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Push new runs
      run: |
          echo $(date) > readme.log.md
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -m 'update new runs' || echo "nothing to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.TOKEN_GITHUB }}
